### ISSUE TITLE
# Work Plan 20160519 # 修改程序

### ISSUE THREAD

**Issue by ClaireWangGoForIt** [ClaireWangGoForIt/learningPoints#2]
先看书：第2本书的第15章（DDL：19日上午9点30）；  
然后想第二项任务中的情形有哪些（DDL：19日上午10点）。  
然后把put500那边的程序移过来，作为original version，开始今天的工作。
- [ ] 打框架（DDL：19日中午）：  
  - [ ] 目标：使用R6的方式构造这个工具，里面有数据也有函数，人家用的时候直接调用需要的功能就行了；  
  - [ ] 步骤：看需要用到哪些数据（可以把数据准备单独包装成小块），人家可能需要哪些功能（根据人家需要的功能包装函数，思考的方式是那个文件下的好几个程序，对应着不同的功能。比如说，calculation,tidy,analyze，其中analyze主要是在画图）；然后用R6的方式把这些东西打散、重构，使之更为清晰。  
- [ ] 使程序更快更适合更多的情形（19日下午5点半）：  
  - [ ] 目标：运行更快，适合更多的情形，别人想到一个什么想用的东西，直接调用就能出结果了；  
  - [ ] 步骤：先想想人家可能需要用这个工具来完成什么样的任务，根据任务内容考虑需要变化哪些变量，然后思考函数的构造方式（比如说if条件，比如说对冲资产的变化，涨跌的变化，按日还是按照对冲的变化，这个涉及对冲方式，所以要考虑下对冲方式有哪些）；根据书上的指引和对程序的梳理来使程序变快。  
- [ ] 改错（19日下午6点半）：  
  - [ ] 目标：之前罗列的三个问题要处理下（就是本子上的三项）;  输出的文件夹得能够直接自建，不需要提前建个文件夹的。
  - [ ] 步骤：一步一步做就是了。  
- [ ] debug（希望bug越少越好…）。

**Comment by ClaireWangGoForIt** [comment]
打框架的任务完成到output，明天接着继续做。
