### ISSUE TITLE
# Work Plan till20160607 # 修改程序

### ISSUE THREAD

**Issue by ClaireWangGoForIt** [ClaireWangGoForIt/learningPoints#4]
- [x] 把框架部分的output文件夹下面的程序写好（DDL：23日中午）：  
  - [x] 目标：使用result.SDF与result.HTF分别展示针对startdate与hedgetrigger的结果。都包括了画图和输出excel。画图都是以spnl和pnl为纵坐标，一个是以日期为横坐标，一个是以hedgetrigger为横坐标。另外，本身的那个.plot是画的行情，可以保留它。  
- [ ] 使程序更快更适合更多的情形（24日下午5点半）：  
  - [ ] 目标：运行更快，适合更多的情形，别人想到一个什么想用的东西，直接调用就能出结果了；  
  - [ ] 步骤：先想想人家可能需要用这个工具来完成什么样的任务，根据任务内容考虑需要变化哪些变量，然后思考函数的构造方式（比如说if条件，比如说对冲资产的变化，涨跌的变化，按日还是按照对冲的变化，这个涉及对冲方式，所以要考虑下对冲方式有哪些）；另外，频率的选取会影响循环的数值的设置，得把这个弄得通用；另外，如果卖出的期权中有看涨又有看跌，要想下那些unique(option$callorput)该怎么办；另外，loopN，multiplier和hedgegap这几个参数要看下是否已经调成对应着可以直接变化的了，不能直接写死的哈。。另外，逐条件进行赋值的变量，最后需要用stopifnot语句来检查赋值列是否还有空值；另外，as.Date的里面都要写上tz = "Asia/Shanghai"，这样说起来是不是直接在global option的地方写上就算了;根据书上的指引和对程序的梳理来使程序变快。  
- [ ] 改错（25日下午6点半）：  
  - [ ] 目标：之前罗列的三个问题要处理下（就是本子上的三项）;  输出的文件夹得能够直接自建，不需要提前建个文件夹的。
  - [ ] 步骤：一步一步做就是了。  
- [ ] debug（希望bug越少越好…）。

**Comment by ClaireWangGoForIt** [comment]
2016-06-03:   
- [x] 看完这个RQuantLib的包（中午之前）;  
- [ ] 继续加速程序：  
  - [x] 用向量化的方法提速（可参照之前的笔记和做法）  
  - [ ] 用包里的函数算价格和希腊值，以节省时间；

**Comment by ClaireWangGoForIt** [comment]
2016-06-06:  
- [ ] task:把barriar做进去，这个的做法是把type调成可以选择的，以方便日后可能还有新的type要加入；对vol值做循环，找到最适合的vol；  
- [ ] 解决上上面那个框里面列出来的问题;

**Comment by ClaireWangGoForIt** [comment]
- [ ] TASK:使程序能够处理多种起止日期的情况，例如，在一个期权组合中，可能包括多个子期权，它们的起止日期是不一定一样的，另外，对于我们的整个期权持仓，里面的期权可能一起做对冲，那么起止日期就更加无法保证一致了。  
  目前的idea：现在的程序是根据datetime的最大值最小值来写入起止日期，但在实际发行产品的时候，起止日期是确定的，于是可以在excel里写入起止日期，然后根据这两个日期来写datetime；  
  另外，想清楚之后要从前到后继续整理一遍程序，看那些与日期有关的处理是否得当。
