### ISSUE TITLE
# Work Plan # 期权平价套利表整理0701-0706

### ISSUE THREAD

**Issue by ClaireWangGoForIt** [ClaireWangGoForIt/learningPoints#6]
任务介绍：根据从数据库中读取的持仓信息，结合行情信息，计算后续指标。目前卡住的地方是，SAS读取了持仓信息之后，不能到万德或天软读取行情信息了。目前想到的解决办法是，用R连接SIRTP数据库之后读取持仓信息和交易信息，连接天软之后读取行情信息，再根据公式计算后续指标。  
任务概况：做四张表（我觉得是四张。。）。   
- [x] 第一张：结果汇总。对正向（买ETF和put，卖call）和负向（卖ETF和put，买call）都计算下列指标：  
  - [x] 开仓次数。（我觉得是根据从数据库读取的数据做汇总计算）  
  - [x] 总价差。（目前就是卡在这里，希望能不再使用excel。我觉得用R连SIRTP数据库和天软数据库能根据代码读出strike，从而解决这个问题。）正向和负向的计算公式都是：call的成交金额-put成交金额+strike*10000-ETF成交金额。  
  - [x] 平均价差。计算公式是：总价差/开仓次数。  
  - [x] 收益率。计算公式是：总价差/ETF成交金额。之所以被除数是这个，是因为套利的成本主要就是来源于ETF吧。  
  - [x] 当日PnL：当日总持仓 - 昨日总持仓 - 当天买入金额 + 当天卖出金额。  
  - [x] 总PnL：当日PnL + 昨日总PnL。  
- [x] 第二张：收盘结果汇总。看师兄列示的表的样式。注意数量是成对计算的，价差的算法是把上面公式中的价格换成收盘价。  
- [x] 第三张：正向明细。  
- [x] 第四张：反向明细。  
  任务提示：需要整理的貌似是4月12至6月30的平价套利结果；取名称的程序在天软师兄的文件夹下的类似component或pnl那样名称的脚本中；其余提示可参照师兄写的白纸。

**Comment by ClaireWangGoForIt** [comment]
接下来需要整改的部分：   
- [x] 对于第二张表中零散期权的展示，最好名称能写得详细一些，而不是只选取后面的几个字符。  
- [x] 20160614的sequence的处理得重新考虑下  
- [x] 第二张表中50ETF与下面的零散的资产是什么关系呢。。。怎么感觉零散的资产也会有50ETF啊。。  
  后来，就不用处理零散的期权的，只看对子。。。
