### ISSUE TITLE
# Work Plan #20160808-20160812

### ISSUE THREAD

**Issue by ClaireWangGoForIt** [ClaireWangGoForIt/learningPoints#8]
- [ ] work:  
  - [ ] rpt.rnw。周一、周二。  
  - [ ] 梳理天软程序：code和optionCode得统一成一个参数；给自己写的函数分类整理下；maybe写个memo也是可以的。周三。  
  - [ ] 看一些做包的东西，至少有个整体思路要怎么做。周四、周五。  
- [ ] study:至少看210面的书。每天30面。每天三个小时看完吧。

**Comment by ClaireWangGoForIt** [comment]
这周先整理出一个RNW的模板，要求：可以在全文使用中文；能画PNL那张表；（先把那张报告写出来看看吧）
